SciNewsSite/SciNewsSite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/',  include('blog.urls'))
]

SciNewsSite/blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),  # 首页
    path('search/submit/', views.on_search_submit, name='search_submit'),  # 提交搜索后中转页面
    path('search/?<str:content>/', views.SearchView.as_view(), name='search'),  # 搜索结果页
    path('search/?<str:content>/?page=<int:page>', views.SearchView.as_view(), name='search_page'),  # 搜索结果页分页
    path('search/?<str:content>/to/', views.search_to_page, name='search_to'),  # 搜索结果页分页中转页面
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail'),  # 详情页
    path('detail/<int:blog_id>/submit/', views.submit_comment, name='submit'),  # 评论提交中转页面
    path('detail/<int:blog_id>/delete/<int:comment_id>/', views.delete_comment, name='delete'),  # 评论删除中转页面
    path('list/', views.ListView.as_view(), name='list'),  # 列表页面
    path('list/to/', views.list_to_page, name='list_to'),  # 列表输入分页中转页面
    path('list/?page=<int:page>', views.ListView.as_view(), name='list_query'),  # 列表分页
    path('category/<str:category>/<int:sub_id>/', views.CategoryResult.as_view(), name='category_result'),  # 分类结果
    path('category/<str:category>/<int:sub_id>/?page=<int:page>', views.CategoryResult.as_view(), name='category_page'),
    # 分类分页
    path('category/<str:category>/<int:sub_id>/to/', views.category_to_page, name='category_to'),  # 分类输入分页中转页面
    path('category/', views.CategoryView.as_view(), name='category'),  # 分类页面)
]

SciNewsSite/blog/models.py
from datetime import datetime

from django.db import models


class Blog(models.Model):
    """
    博客（新闻）模型，初始化时必须初始化的变量是:
    url - 网页链接
    website - 新闻网站
    title - 新闻网站
    author_id - 作者ID
    create_time - 创建时间
    text - 正文文字
    """
    url = models.URLField(max_length=100, unique=True)  # 网页链接
    website = models.CharField(max_length=20, default="")  # 新闻网站
    title = models.CharField(max_length=100)  # 新闻标题
    author_id = models.CharField(max_length=50)  # 作者ID
    author_img = models.CharField(max_length=100, blank=True)  # 作者头像，基本上都没有
    fans = models.IntegerField(default=0)  # 粉丝数，基本上都没有
    create_time = models.DateTimeField(blank=True)  # 创建时间
    read_num = models.IntegerField(default=0)  # 阅读量，基本上都没有
    likes = models.IntegerField(default=0)  # 点赞数，基本上都没有
    text = models.TextField(blank=True)  # 正文文字
    theme = models.CharField(max_length=20, default="")  # 主题

    def get_time_category(self):
        """
        获取时间分类
        :return: 时间分类： 1 - 近三月 | 2 - 近一年（不包括近三月） | 3 - 一年前
        """
        now = datetime.now()
        if (now - self.create_time).days <= 90:
            return 1
        elif (now - self.create_time).days <= 365:
            return 2
        return 3

    def __str__(self):
        return f"{self.title} | {self.author_id}"


class Image(models.Model):
    """
    图像模型，初始化时必须初始化的变量：
    blog - 关联的blog的id
    image_path - 图像路径，为相对于static/blog/images/的路径
    """
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)  # 外键-博客（新闻）
    image_path = models.CharField(max_length=50)  # 图像路径

    def __str__(self):
        return f"{str(self.blog)} | {self.image_path}"


class Comment(models.Model):
    """
    评论模型，初始化时必须初始化的变量：
    blog - 关联的blog的id
    user_id - 用户名
    comment_content - 评论内容，非空
    发表时间自动填充，不可修改
    """
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE)
    user_id = models.CharField(max_length=50)
    comment_content = models.CharField(max_length=1000)
    create_time = models.DateTimeField(auto_now_add=True)  # 创建时间,自动填充

    def __str__(self):
        return f"{str(self.blog)} | comment from {self.user_id}"


class Word(models.Model):
    """
    词模型，初始化时必须初始化的变量：
    blogs - 关联的blog的id，格式为 1,2,3,4
    word - 词
    frequency - 词频，默认为0
    dic_order - 字典序，主键
    """
    word = models.CharField(max_length=50)
    blogs = models.TextField()
    frequency = models.IntegerField(default=0)
    dic_order = models.IntegerField(primary_key=True)

    def __str__(self):
        return f"{str(self.word)} | {self.blogs}"

SciNewsSite/blog/views.py
import datetime
import re
import time
import jieba

from django.db.models import Q
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from .models import Blog, Comment, Image, Word


class DetailView(generic.DetailView):
    """新闻详情页"""
    template_name = 'blog/detail.html'  # 设置模板
    model = Blog  # 设置model
    blog = None

    def get_queryset(self):
        self.blog = get_object_or_404(Blog, id=self.kwargs['pk'])  # 获取blog
        self.blog.read_num += 1  # 阅读量加1 （初始化时）
        self.blog.save()  # 保存更改
        return Blog.objects.filter(id=self.kwargs['pk'])

    def get(self, request, *args, **kwargs):
        if self.blog is not None:  # 如果已经初始化就加一
            self.blog.read_num += 1
            self.blog.save()  # 保存更改
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['blog'] = self.blog  # 将blog添加到上下文
        # 将图片添加至上下文
        context['images'] = Image.objects.filter(blog_id=self.blog.id)
        # 将评论添加至上下文
        context['comments'] = Comment.objects.filter(blog_id=self.blog.id).order_by('-create_time')
        context['comments_num'] = len(context['comments'])
        # 时间分类
        time_cat = ["", "近三月", "近一年", "一年前"]
        context['time_cat'] = time_cat[self.blog.get_time_category()]
        # 切割正文
        context['content'] = self.blog.text.split("\n")
        return context


def submit_comment(request, blog_id):
    """提交评论函数"""
    blog = get_object_or_404(Blog, pk=blog_id)  # 获取blog
    try:
        user_name = request.POST['user_name']  # 获取用户名
        comment_content = request.POST['comment_area']  # 获取评论内容

        # 没有评论内容直接返回
        if len(comment_content) == 0:
            return HttpResponseRedirect(reverse('blog:detail', kwargs={'pk': blog_id}))  # 重定向回详情页

        # 没有用户名则为“匿名用户”
        if len(user_name) == 0:
            user_name = "匿名用户"

    except Exception as e:
        print(e)
    else:
        # 将评论保存到数据库
        comment = Comment(user_id=user_name, comment_content=comment_content, blog_id=blog.id)
        comment.save()
        return HttpResponseRedirect(reverse('blog:detail', kwargs={'pk': blog_id}))  # 重定向回详情页


def delete_comment(request, blog_id, comment_id):
    """删除评论函数"""
    try:
        comment = Comment.objects.get(id=comment_id)
        comment.delete()  # 删除选中评论

    except Exception as e:
        print(e)
    else:
        return HttpResponseRedirect(reverse('blog:detail', kwargs={'pk': blog_id}))  # 重定向回详情页


class ListView(generic.ListView):
    """新闻列表视图"""
    model = Blog
    template_name = 'blog/list.html'
    context_object_name = 'blogs'
    paginate_by = 20  # 每页中对象数量

    def get_queryset(self):
        """获取新闻列表"""
        return Blog.objects.all()

    def get_context_data(self, **kwargs):
        context = super(ListView, self).get_context_data(**kwargs)

        #  获取评论数量
        comment_num_dic = {}
        for blog in context['blogs']:
            comment_num_dic[blog.id] = blog.comment_set.all().count()
        context['comment_num_dic'] = comment_num_dic

        # 获取正文前50个字符
        text_dic = {}
        for blog in context['blogs']:
            if len(blog.text) > 50:
                text_dic[blog.id] = blog.text[:50] + '...'
            else:
                text_dic[blog.id] = blog.text
        context['text_dic'] = text_dic

        return context


def list_to_page(request):
    """列表页跳转至指定页面函数"""
    try:
        page = int(request.POST['page_number'])  # 获取页码
        if page <= 0:
            raise Http404('页面不存在')
    except Exception as e:
        print(e)
        raise Http404('页面不存在')  # 抛出404错误
    else:
        return HttpResponseRedirect(reverse('blog:list_query', kwargs={'page': page}))  # 重定向回列表页


class IndexView(generic.ListView):
    """主页"""
    model = Blog
    template_name = 'blog/index.html'
    context_object_name = "blogs"

    def get_queryset(self):
        if Blog.objects.all().count() < 20:  # 小于20条，返回全部
            return Blog.objects.all()
        return Blog.objects.all().order_by('?')[:20]  # 随机排序

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)

        #  获取评论数量
        comment_num_dic = {}
        for blog in context['blogs']:
            comment_num_dic[blog.id] = blog.comment_set.all().count()
        context['comment_num_dic'] = comment_num_dic

        # 获取正文前50个字符
        text_dic = {}
        for blog in context['blogs']:
            if len(blog.text) > 50:
                text_dic[blog.id] = blog.text[:50] + '...'
            else:
                text_dic[blog.id] = blog.text
        context['text_dic'] = text_dic

        return context


def on_search_submit(request):
    """处理首页搜索框提交的函数"""
    try:
        search_text = request.POST['search_input']  # 获取搜索框中内容
        order_choice = request.POST['order_group']  # 获取排序方式
        from_choice = '+'.join(request.POST.getlist('from_checkbox'))  # 获取分类“来源”
        time_choice = '+'.join(request.POST.getlist('time_checkbox'))  # 获取分类“时间”
        theme_choice = '+'.join(request.POST.getlist('theme_checkbox'))  # 获取分类“主题”
    except Exception as e:
        print(e)
        return Http404('搜索过程出现错误')
    else:
        # 重定向到搜索页
        return HttpResponseRedirect(
            reverse('blog:search', kwargs={
                'content': f"text={search_text}&order={order_choice}&from={from_choice}&time={time_choice}&theme={theme_choice}"}))


class SearchView(generic.ListView):
    """搜索结果页"""
    model = Blog
    template_name = 'blog/search.html'
    context_object_name = 'blogs'
    paginate_by = 20  # 每页中对象数量
    search_num = 0  # 条目数
    search_time_ms = 0  # 搜索耗时
    cut = False  # 是否采用分词匹配
    search_text = ""
    order_choice = ""
    from_choice = ""
    time_choice = ""
    theme_choice = ""

    def get_queryset(self):
        begin_time = time.time()  # 搜索开始时间戳

        try:
            self.search_text = re.findall('text=([^&]+)', self.kwargs['content'])[0]  # 搜索文字
            self.order_choice = re.findall('order=([^&]+)', self.kwargs['content'])[0]  # 排序
            self.from_choice = re.findall('from=([^&]*)', self.kwargs['content'])[0]  # 来源
            self.time_choice = re.findall('time=([^&]*)', self.kwargs['content'])[0]  # 时间
            self.theme_choice = re.findall('theme=([^&]*)', self.kwargs['content'])[0]  # 主题

            word_qs = Word.objects.filter(word__iexact=self.search_text)  # 精确搜索
            blog_set = Blog.objects.none()
            if word_qs.count() == 0:  # 没有匹配
                # 尝试全文匹配
                blog_set |= (Blog.objects.filter(title__icontains=self.search_text) | Blog.objects.filter(
                    text__icontains=self.search_text))
                if blog_set.count() == 0:
                    # 完全匹配失败，尝试分词后再匹配
                    cut_ls = jieba.cut_for_search(self.search_text)  # 分词
                    for word in cut_ls:
                        word_qs |= Word.objects.filter(word__iexact=word)
                    for word in word_qs:
                        blog_set |= Blog.objects.filter(id__in=word.blogs.split(','))
                    self.cut = True
            else:
                for word in word_qs:
                    blog_set |= Blog.objects.filter(id__in=word.blogs.split(','))
        except Exception as e:  # 如果出现错误
            print(e)
            end_time = time.time()  # 搜索结束时间戳
            self.search_time_ms = int(round((end_time - begin_time) * 1000))  # 搜索耗时（毫秒）
            return Blog.objects.none()  # 返回空列表
        else:
            # 按照分类筛选
            # 来源分类
            website_ls = []
            if '1' in self.from_choice:
                website_ls.append("网易新闻")
            if '2' in self.from_choice:
                website_ls.append("新浪新闻")
            if '3' in self.from_choice:
                website_ls.append("IT之家")
            if len(website_ls) == 0:  # 全部选中
                website_ls = ['网易新闻', '新浪新闻', 'IT之家']

            # 时间分类
            time_ls = self.time_choice.split('+')
            if len(time_ls) == 0:  # 全部选中
                time_ls = ['1', '2', '3']

            # 自定义Q, 用于时间分类筛选
            time_q = Q()
            for time_num in time_ls:
                if time_num == '1':  # 近三月
                    time_q |= Q(create_time__gte=datetime.datetime.now() - datetime.timedelta(days=90))
                if time_num == '2':  # 近一年
                    time_q |= Q(create_time__lt=datetime.datetime.now() - datetime.timedelta(days=90),
                                create_time__gte=datetime.datetime.now() - datetime.timedelta(days=365))
                if time_num == '3':  # 一年前
                    time_q |= Q(create_time__lt=datetime.datetime.now() - datetime.timedelta(days=365))

            # 主题分类
            theme_ls = []
            if '1' in self.theme_choice:
                theme_ls.append('科技产品')
            if '2' in self.theme_choice:
                theme_ls.append('AI')
            if '3' in self.theme_choice:
                theme_ls.append('财经')
            if '4' in self.theme_choice:
                theme_ls.append('其他')
            if len(theme_ls) == 0:  # 全部选中
                theme_ls = ['科技产品', 'AI', '财经', '其他']

            blog_set = blog_set.filter(website__in=website_ls).filter(
                time_q).filter(theme__in=theme_ls)  # 获取符合要求的所有blog

            self.search_num = blog_set.count()  # 搜索结果条目数

            # 排序
            if self.order_choice == '1':
                blog_set = blog_set.order_by('-create_time')  # 按时间从新到旧排序
            elif self.order_choice == '2':
                blog_set = blog_set.order_by('-read_num')  # 按浏览量从高到低排序

            end_time = time.time()  # 搜索结束时间戳
            self.search_time_ms = int(round((end_time - begin_time) * 1000))  # 搜索耗时（毫秒）

            return blog_set

SciNewsSite/blog/templates/blog/detail.html
<!doctype html>
<html>
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SciNews | {{ blog.title }}</title>
    <link rel="icon" href="{% static 'blog/images/head.png' %}" sizes="16x16">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/detailStyle.css' %}">
    <script src="http://use.edgefonts.net/montserrat:n4:default;source-sans-pro:n2:default.js"
            type="text/javascript"></script>
</head>

<body>
<div id="mainwrapper">
    <header>
        <div id="logo">SciNews</div>
        <nav><a href="{% url 'blog:index' %}" title="Link">首页</a> <a href="{% url 'blog:list' %}"
                                                                       title="Link">列表</a><a
                href="{% url 'blog:category' %}" title="Link">分类</a></nav>
    </header>
    <div id="content">
        <section id="mainContent">
            <!-- 新闻标题 -->
            <h1 id="blog_title">{{ blog.title }}</h1>
            <!-- 新闻发布日期与作者 -->
            <div id="blog_info">
                <span id="pub_date">{{ blog.create_time }}</span>
                <span id="author_name">{{ blog.author_id }}</span>
            </div>
            <!-- 新闻分类 -->
            <div id="category">
                <span id="category_website">{{ blog.website }}</span>
                <span id="category_time">{{ time_cat }}</span>
                <span id="category_theme">{{ blog.theme }}</span>
            </div>

            <!-- 正文 -->
            <div id="body_text">
                {% for t in content %}
                    <p>{{ t }}</p>
                {% endfor %}
            </div>

            <!-- 正文中的图片-->
            <div id="otherImage">
                {% for image in images %}
                    <img src="/static/blog/images/{{ image.image_path }}" alt=""/>
                {% endfor %}
            </div>
            <!-- 阅读量 -->
            <div id="readNum">
                <span>阅读量 : <a id="readNum_num">{{ blog.read_num }}</a></span>
            </div>
            <!-- 原文链接 -->
            <div id="link">
                <span>原文链接 : <a href="{{ blog.url }}">{{ blog.url }}</a></span>
            </div>

            <HR width="100%" color=gray SIZE=0.5>
            <!-- 评论区-->
            <div id="comments">
                <h2>评论<span id="commentsNum">{{ comments_num }}</span></h2>
                <!-- 评论表单-->
                <form action="{% url 'blog:submit' blog.id %}" id="comment_form" method="post">
                    {% csrf_token %}
                    <div>用户名：<input id="user_name" name="user_name"/></div>
                    <div>
                        <textarea id="comment_area" name="comment_area" rows="6" cols="50"
                                  maxlength="1000">请输入您的评论</textarea>
                    </div>
                    <input id="comment_submit" type="submit"/>
                </form>
                <!-- 已发表过的评论 -->
                {% if comments_num != 0 %}
                    {% for comment in comments %}
                        <div class="user_comment">
                            <a href="{% url 'blog:delete' blog.id comment.id %}"><img
                                    src="{% static 'blog/images/delete.png' %}"></a>
                            <span class="user_name"
                                  style="font-size: 16px; font-weight: 600; color: rgba(86, 86, 86, 1.00);margin-bottom: 10px;">
                {{ comment.user_id }}</span>
                            <span class="comment_time">  发布于<span>{{ comment.create_time }}</span></span>
                            <br>
                            <br>
                            <span class="comment_content">{{ comment.comment_content }}</span>
                        </div>
                    {% endfor %}
                {% endif %}
            </div>
        </section>

        <footer>

        </footer>
    </div>
    <div id="footerbar"></div>
</div>
</body>
</html>

SciNewsSite/blog/templates/blog/search.html
<!doctype html>
<html>
{% load static %}
{% load dicFilter %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>SciNews | 搜索页</title>
    <link rel="icon" href="{% static 'blog/images/head.png' %}" sizes="16x16">
    <link rel="stylesheet" type="text/css" href="{% static 'blog/searchStyle.css' %}">
    <script src="http://use.edgefonts.net/montserrat:n4:default;source-sans-pro:n2:default.js"
            type="text/javascript"></script>
</head>

<body>
<div id="mainwrapper">
    <header>
        <div id="logo">SciNews</div>
        <nav><a href="{% url 'blog:index' %}" title="Link">首页</a> <a href="{% url 'blog:list' %}"
                                                                       title="Link">列表</a><a
                href="{% url 'blog:category' %}" title="Link">分类</a></nav>
    </header>
    <div id="content">
        <section id="mainContent">
            <h1>搜索结果</h1>

            <!-- 搜索区域 -->
            <div id="search_area">
                <form id="search_form" method="post" action="{% url 'blog:search_submit' %}">
                    {% csrf_token %}
                    <!-- 搜索框 -->
                    <input maxlength="50" id="search_input" name="search_input" value="{{ search_text }}">
                    <!-- 提交按钮 -->
                    <input id="submit_btn" type="submit" name="submit_btn" value="搜索">
                    <div id="area_wrapper">
                        <!-- 单选区 -->
                        <div id="radio_area">
                            <a>排序依据: </a>
                            <label>
                                {% if order_choice == '1' %}
                                    <input type="radio" id="order_by_time" name="order_group" value="1" checked>
                                {% else %}
                                    <input type="radio" id="order_by_time" name="order_group" value="1">
                                {% endif %}
                                <span>按时间排序(由新到旧)</span>
                            </label>
                            <label>
                                {% if order_choice == '2' %}
                                    <input type="radio" id="order_by_hot" name="order_group" value="2" checked>
                                {% else %}
                                    <input type="radio" id="order_by_hot" value="2" name="order_group">
                                {% endif %}
                                <span>按热度排序(由高到低)</span>
                            </label>
                        </div>
                        <!-- 多选区 -->
                        <div id="check_box_area_1">
                            <a>新闻来源:</a>
                            <label>
                                {% if "1" in from_choice %}
                                    <input type="checkbox" id="from_163" value="1" name="from_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="from_163" value="1" name="from_checkbox">
                                {% endif %}
                                <span>网易新闻</span>
                            </label>
                            <label>
                                {% if "2" in from_choice %}
                                    <input type="checkbox" id="from_sino" value="2" name="from_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="from_sino" value="2" name="from_checkbox">
                                {% endif %}
                                <span>新浪新闻</span>
                            </label>
                            <label>
                                {% if "3" in from_choice %}
                                    <input type="checkbox" id="from_ithome" value="3" name="from_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="from_ithome" value="3" name="from_checkbox">
                                {% endif %}
                                <span>IT之家</span>
                            </label>
                        </div>

                        <div id="check_box_area_2">
                            <a>发布时间:</a>
                            <label>
                                {% if "1" in time_choice %}
                                    <input type="checkbox" id="last_3_months" value="1" name="time_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="last_3_months" value="1" name="time_checkbox">
                                {% endif %}
                                <span>近三月</span>
                            </label>
                            <label>
                                {% if "2" in time_choice %}
                                    <input type="checkbox" id="last_year" value="2" name="time_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="last_year" value="2" name="time_checkbox">
                                {% endif %}
                                <span>近一年</span>
                            </label>
                            <label>
                                {% if "3" in time_choice %}
                                    <input type="checkbox" id="earlier" value="3" name="time_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="earlier" value="3" name="time_checkbox">
                                {% endif %}
                                <span>一年前</span>
                            </label>
                        </div>

                        <div id="check_box_area_3">
                            <a>新闻主题:</a>
                            <label>
                                {% if '1' in theme_choice %}
                                    <input type="checkbox" id="product" value="1" name="theme_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="product" value="1" name="theme_checkbox">
                                {% endif %}
                                <span>科技产品</span>
                            </label>
                            <label>
                                {% if '2' in theme_choice %}
                                    <input type="checkbox" id="ai" value="2" name="theme_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="ai" value="2" name="theme_checkbox">
                                {% endif %}
                                <span>AI</span>
                            </label>
                            <label>
                                {% if '3' in theme_choice %}
                                    <input type="checkbox" id="finance" value="3" name="theme_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="finance" value="3" name="theme_checkbox">
                                {% endif %}
                                <span>财经</span>
                            </label>
                            <label>
                                {% if '4' in theme_choice %}
                                    <input type="checkbox" id="others" value="4" name="theme_checkbox" checked>
                                {% else %}
                                    <input type="checkbox" id="others" value="4" name="theme_checkbox">
                                {% endif %}
                                <span>其他</span>
                            </label>
                        </div>
                    </div>

                </form>
            </div>

            <!-- 搜索后台信息 -->
            <div id="search_data">
                {% if cut %}
                    <span>未找到完全匹配结果，已启用分词匹配  | </span>
                {% endif %}
                <span>共 <a id="search_num">{{ search_num }}</a> 条， 用时 <a
                        id="time">{{ search_time_ms }}</a> ms</span>
            </div>

            <!-- 新闻列表 -->
            <table id="content_table">
                <thead id="table_head">
                <th width="70%">新闻</th>
                <th width="10%">作者</th>
                <th width="5%">阅读量</th>
                <th width="5%">评论数</th>
                <th>时间</th>
                </thead>
                <tbody id="table_body">
                {% for blog in blogs %}
                    <tr>
                        <td class="c_title"><a
                                href="{% url 'blog:detail' blog.id %}">{{ blog.title }}</a>
                            <span><br>{{ text_dic|key:blog.id  }}</span></td>
                        <td class="c_author">{{ blog.author_id }}</td>
                        <td class="c_read_num">{{ blog.read_num }}</td>
                        <td class="c_comment_num">{{ comment_num_dic|key:blog.id }}</td>
                        <td class="c_time">{{ blog.create_time }}</td>
                    </tr>
                {% endfor %}
                </tbody>

            </table>

            <!-- 页码导航 -->
            <div id="button_area">
                <!-- 页码按钮导航 -->
                {% if page_obj.has_previous %}
                    <a id="former_page" href="%3Fpage={{ page_obj.previous_page_number }}">上一页</a>
                {% endif %}

                <!-- 当前页为首页 -->
                {% if page_obj.number == 1 %}
                    <a class="this_page" href='%3Fpage=1'>1</a>
                    {% if paginator.num_pages > 3 %}
                        <a class="page_button" href='%3Fpage=2'>2</a>
                        <a class="page_button" href="%3Fpage=3">3</a>
                        <a class="dots">...</a>
                        <a class="page_button"
                           href="%3Fpage={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% elif paginator.num_pages == 3 %}
                        <a class="page_button" href="%3Fpage=2">2</a>
                        <a class="page_button" href="%3Fpage=3">3</a>
                    {% elif paginator.num_pages == 2 %}
                        <a class="page_button" href="%3Fpage=2">2</a>
                    {% endif %}

                    <!-- 当前页为尾页 -->
                {% elif page_obj.number == paginator.num_pages %}
                    <a class="page_button" href="%3Fpage=1">1</a>
                    <a class="dots">...</a>
                    <a class="this_page"
                       href="%3Fpage={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>

                    <!-- 当前页为中间页 -->
                {% else %}

                    <!-- 前页不是1，添加省略号 -->
                    {% if page_obj.previous_page_number != 1 %}
                        <a class="page_button" href="%3Fpage=1">1</a>
                        <a class="dots">...</a>
                    {% endif %}


                    <a class="page_button"
                       href="%3Fpage={{ page_obj.previous_page_number }}">{{ page_obj.previous_page_number }}</a>
                    <a class="this_page" href="%3Fpage={{ page_obj.number }}">{{ page_obj.number }}</a>
                    <a class="page_button"
                       href="%3Fpage={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }}</a>

                    <!-- 后页不是尾页，添加省略号 -->
                    {% if page_obj.next_page_number != paginator.num_pages %}
                        <a class="dots">...</a>
                        <a class="page_button"
                           href="%3Fpage={{ paginator.num_pages }}">{{ paginator.num_pages }}</a>
                    {% endif %}
                {% endif %}

                {% if page_obj.has_next %}
                    <a id="latter_page" href="%3Fpage={{ page_obj.next_page_number }}">下一页</a>
                {% endif %}


            </div>
            <!-- 输入导航 -->
            <div id="input_area">
                <form id="number_form" method="post" action="{% url 'blog:search_to' content %}">
                    {% csrf_token %}
                    <a id="page_label">page:</a>
                    <input id="page_number" name="page_number" type="number" value="{{ page_obj.number }}">
                    <input id="submit_button" type="submit" value="GO">
                </form>
            </div>

        </section>
        <footer>

        </footer>
    </div>
    <div id="footerbar"></div>
</div>
</body>
</html>